.\" Manpage for LogicCalc.
.\" Contact ez.steinberg@yahoo.fr to correct errors or typos.
.TH man 1 "14 May 2019" "1.0" "LogicCalc man page"
.SH NAME
LogicCalc \- a logical calculator
.SH SYNOPSIS
logiccalc
.SH DESCRIPTION
LogicCalc is a simple logic calculator that can compute basic logic functions as AND, OR, NAND etc...
There are two constants, true and false, that are not case-sensitives. You can enter 0 and 1 too.
.SH EXAMPLE
$ logicCalculator 
.br
? (true or false) nand true 
.br
False
.br
? false or false or true
.br
True
.SH SEE ALSO
bc(1)
.SH BUGS
No known bugs.
.SH AUTHOR
STEINBERG Ezriel(ez.steinberg@yahoo.fr)